<?php
function generate_patient_report($test_name, $referred_by, $diagnosed_by, $impression, $technician_name, $report_date, $file_link)
{
    echo '
     <div style="padding-top: 10px;padding-bottom: 10px;">
                        <div class="row" style="margin: 0px;margin-top: 0px;margin-bottom: 0px;">
                            <div class="col">
                                <div class="card border-dark shadow-sm">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-xl-9" style="padding: 14px;padding-top: 10px;">
                                                <h1 style="font-size: 24px;">' . $test_name . '</h1>
                                            </div>
                                            <div class="col-xl-4">
                                                <div style="margin-left: 0px;">
                                                    <div class="row">
                                                        <div class="col">
                                                            <p><b>Referred by: </b> ' . $referred_by . '</p>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col">
                                                            <p><b>Diagnosed by: </b> ' . $diagnosed_by . '</p>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col">
                                                            <p><b>Impression: </b> ' . $impression . '</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-8">
                                                <div>
                                                    <div class="row">
                                                        <div class="col">
                                                            <p><b>Report generated by: </b> ' . $technician_name . '</p>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col">
                                                            <p><b>Report generated on: </b> ' . $report_date . '</p>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col">
                                                            <p><a href="../' .  $file_link  . '">REPORT FILE</a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>';
}
